/**
 * GET /install
 *   → returns a Bash script the user pipes to `bash` to install the CLI and
 *     auto-link their terminal session to the browser tab on /connect.
 *
 * The script:
 *   1. Detects OS (macOS / Linux). Windows users get a friendly hint.
 *   2. Verifies Node 18+ is installed (errors with link if missing).
 *   3. git clone the events-x-marble repo into ~/.events-x-marble/repo
 *      (or git pull if already present).
 *   4. cd packages/cli; npm install --omit=dev (pulls marble from github URL).
 *   5. Symlinks ~/.local/bin/events-x-marble for convenience.
 *   6. Runs `events-x-marble init --connect-session <session>` so the
 *      polling browser tab on /connect can detect the registration.
 *
 * The `?session=cnx_xxx` query is forwarded as --connect-session to the CLI.
 * The repo URL can be overridden via env var EXM_REPO_URL on the server, so
 * the user can ship under their own GitHub org without code changes.
 */
import { Hono } from "hono";
import { env } from "../env.ts";

export const installApp = new Hono();

// Default repo location. Override on the server via env EXM_REPO_URL if you
// host the repo elsewhere. The repo MUST contain packages/cli/.
const DEFAULT_REPO_URL =
  process.env.EXM_REPO_URL ?? "https://github.com/AlexShrestha/events-x-marble";

installApp.get("/", (c) => {
  const session = c.req.query("session") ?? "";
  const cityHint = c.req.query("city") ?? "";
  const baseUrl = env.SITE_URL.replace(/\/$/, "");
  const script = buildInstallScript({ session, cityHint, repoUrl: DEFAULT_REPO_URL, baseUrl });
  c.header("Content-Type", "text/x-shellscript; charset=utf-8");
  c.header("Cache-Control", "no-cache");
  return c.body(script);
});

function buildInstallScript({
  session,
  cityHint,
  repoUrl,
  baseUrl,
}: {
  session: string;
  cityHint: string;
  repoUrl: string;
  baseUrl: string;
}): string {
  const sessionArg = session ? `--connect-session "${shellEscape(session)}"` : "";
  // Note: even with cityHint set, register.ts will override from the session's
  // geo headers — so we only forward this as a fallback when no session geo
  // is available (e.g. dev with no Vercel headers).
  const cityArg = cityHint ? `--city "${shellEscape(cityHint)}"` : "";
  return `#!/usr/bin/env bash
# events-x-marble installer
# Generated by ${baseUrl}/install?session=${encodeURIComponent(session || "(none)")}
# This script is intentionally small. It clones the public CLI repo into
# ~/.events-x-marble/repo, installs deps, and runs the init flow linked to
# your browser tab on /connect.

set -euo pipefail

# ---- Pretty printing ------------------------------------------------------
say()  { printf "\\033[1;36m▸\\033[0m %s\\n" "$*"; }
ok()   { printf "\\033[1;32m✓\\033[0m %s\\n" "$*"; }
warn() { printf "\\033[1;33m!\\033[0m %s\\n" "$*"; }
die()  { printf "\\033[1;31m✗ %s\\033[0m\\n" "$*" >&2; exit 1; }

INSTALL_ROOT="\${HOME}/.events-x-marble"
REPO_DIR="\${INSTALL_ROOT}/repo"
CLI_DIR="\${REPO_DIR}/packages/cli"
BIN_DIR="\${HOME}/.local/bin"
SITE_URL="${baseUrl}"
REPO_URL="${repoUrl}"

# ---- OS check -------------------------------------------------------------
case "$(uname -s)" in
  Darwin) OS="macos" ;;
  Linux)  OS="linux" ;;
  *)      die "unsupported OS: $(uname -s). events-x-marble currently supports macOS and Linux. Windows support is on the roadmap." ;;
esac
say "detected $OS"

# ---- Pre-flight: existing marble KG? -------------------------------------
# Before the 30s clone + npm install, scan a few common locations for an
# existing marble KG. If found, we tell the user upfront so they know this
# install will take ~1 min (just scoring) instead of ~5–8 min (full ingest +
# learn pipeline). The init step will re-validate and actually use it.
EXISTING_KG=""
for candidate in \\
  "\${HOME}/.events-x-marble/marble-kg.json" \\
  "\${HOME}/marble-kg.json" \\
  "\${HOME}/Downloads/marble-kg.json" \\
  ; do
  if [ -f "\$candidate" ]; then EXISTING_KG="\$candidate"; break; fi
done
# Glob ~/Downloads for *marble-kg*.json variants (e.g. alex-marble-kg-full.json).
if [ -z "\$EXISTING_KG" ] && [ -d "\${HOME}/Downloads" ]; then
  for candidate in "\${HOME}/Downloads"/*marble[-_]kg*.json "\${HOME}/Downloads"/*marble[-_]graph*.json; do
    [ -f "\$candidate" ] || continue
    EXISTING_KG="\$candidate"
    break
  done
fi
if [ -n "\$EXISTING_KG" ]; then
  ok "found existing marble KG at \$EXISTING_KG"
  say "fast path — we'll use it directly (no rebuild). Total time ~1 min."
else
  say "no existing marble KG found — we'll build one from your data (~5–8 min)."
fi


# ---- Prerequisite check: Node 18+ ----------------------------------------
if ! command -v node >/dev/null 2>&1; then
  die "Node.js 18+ is required but not installed. Install it from https://nodejs.org/en/download (or via 'brew install node' on macOS) and re-run this installer."
fi
NODE_MAJOR=$(node -p 'parseInt(process.versions.node.split(".")[0], 10)')
if [ "$NODE_MAJOR" -lt 18 ]; then
  die "Node \${NODE_MAJOR} is too old. events-x-marble needs Node 18 or later."
fi
ok "Node $(node -v) detected"

# ---- Prerequisite check: git ---------------------------------------------
if ! command -v git >/dev/null 2>&1; then
  die "git is required but not installed. On macOS run 'xcode-select --install'; on Linux use your package manager."
fi
ok "git detected"

# ---- Clone or update the CLI repo ----------------------------------------
mkdir -p "\${INSTALL_ROOT}"
if [ -d "\${REPO_DIR}/.git" ]; then
  say "updating existing repo at \${REPO_DIR}…"
  (cd "\${REPO_DIR}" && git fetch --quiet origin && git reset --quiet --hard origin/HEAD)
else
  say "cloning \${REPO_URL} → \${REPO_DIR}…"
  git clone --depth=1 --quiet "\${REPO_URL}" "\${REPO_DIR}"
fi
ok "repo ready"

if [ ! -d "\${CLI_DIR}" ]; then
  die "expected packages/cli/ in the cloned repo at \${CLI_DIR} — was the repo URL correct?"
fi

# ---- Install npm deps ----------------------------------------------------
say "installing CLI dependencies (this can take ~30s the first time)…"
(cd "\${CLI_DIR}" && npm install --omit=dev --no-audit --no-fund --silent)
ok "dependencies installed"

# ---- Symlink the binary into ~/.local/bin -------------------------------
mkdir -p "\${BIN_DIR}"
ln -sf "\${CLI_DIR}/bin/exm.mjs" "\${BIN_DIR}/events-x-marble"
chmod +x "\${CLI_DIR}/bin/exm.mjs"
ok "linked \${BIN_DIR}/events-x-marble"

case ":\${PATH}:" in
  *":\${BIN_DIR}:"*) ;;
  *) warn "\${BIN_DIR} is not in your PATH. Add this to your shell profile:
       export PATH=\\"\${BIN_DIR}:\\$PATH\\"
     For this session, we'll invoke events-x-marble by its full path." ;;
esac

# ---- Kick off the interactive init linked to your browser tab -----------
echo ""
say "starting init… (your browser tab will auto-redirect when this finishes)"
echo ""

# When the user invoked us via \`curl … | bash\`, this shell's stdin is the curl
# pipe (already drained by reading the script body) — so any subsequent prompts
# would read EOF and the init would hang forever asking "use this? [Y/n]".
# Redirecting stdin from /dev/tty pulls input directly from the user's terminal
# regardless of how this script was piped in.
if [ -t 0 ]; then
  STDIN_SRC=/dev/stdin
elif [ -e /dev/tty ]; then
  STDIN_SRC=/dev/tty
else
  warn "no controllable terminal detected — falling back to /dev/null"
  STDIN_SRC=/dev/null
fi

# ---- Pass B: env-var pass-through for non-interactive setups -------------
# These let the user pre-set their answers via env vars instead of prompts,
# useful for \`EXM_BUILD_FROM=/path/to/data.json curl ... | bash\`.
EXTRA_ARGS=()
if [ -n "\${EXM_BUILD_FROM:-}" ]; then
  if [ ! -e "\${EXM_BUILD_FROM}" ]; then
    die "\$EXM_BUILD_FROM points at a missing file: \${EXM_BUILD_FROM}"
  fi
  EXTRA_ARGS+=(--build-from "\${EXM_BUILD_FROM}")
  say "will build a fresh marble KG from \${EXM_BUILD_FROM}"
fi
if [ -n "\${EXM_KG_FORMAT:-}" ]; then
  EXTRA_ARGS+=(--kg-format "\${EXM_KG_FORMAT}")
fi
if [ -n "\${EXM_CITY:-}" ]; then
  EXTRA_ARGS+=(--city "\${EXM_CITY}")
fi
# --kg-path takes priority order: env override > pre-flight bash scan > init's
# own pickKgPath fallback. EXISTING_KG was populated above by the pre-flight.
if [ -n "\${EXM_KG_PATH:-}" ]; then
  EXTRA_ARGS+=(--kg-path "\${EXM_KG_PATH}")
elif [ -n "\$EXISTING_KG" ]; then
  EXTRA_ARGS+=(--kg-path "\$EXISTING_KG")
fi

# Safe array expansion under \`set -u\` — bash 3.2 (macOS default) treats
# "\${EXTRA_ARGS[@]}" on an empty array as "unbound variable" and aborts. The
# \${arr[@]+"\${arr[@]}"} idiom expands to the array when it has elements and
# to NOTHING otherwise, which is what we want.
exec < "\${STDIN_SRC}" "\${CLI_DIR}/bin/exm.mjs" init \\
  --site-url "\${SITE_URL}" \\
  ${sessionArg} \\
  ${cityArg} \\
  --no-cron \\
  --auto-first-run \\
  \${EXTRA_ARGS[@]+"\${EXTRA_ARGS[@]}"}
`;
}

function shellEscape(s: string): string {
  return s.replace(/[^A-Za-z0-9_.@:/-]/g, "");
}
